### ISSUE TITLE
ERROR: HTTP error Error in SSL handshake

### ISSUE THREAD

**Issue by b4ll** [Southclaws/pawn-requests#34]
I compiled plugin successfully on my virtual machine, I had to update websocket. I use this plugin because I want to send messages from samp server to discord channel using discord's webhook.

```
//OnGameModeInit
gDiscordWebhook = RequestsClient("https://discordapp.com/api/webhooks/635572759094755338/oqP-j3mJuAMSiRJ3CujcoJVo7GrcqdqAJ_ydaU4-3KOL7Z3f_TOltHaM5raJig9J8uP_");

//OnPlayerText
RequestJSON
(
	gDiscordWebhook,
	"",
	HTTP_METHOD_POST,
	"OnPostJson",
	JsonObject
	(
	 "username", JsonString(gPlayerData[playerid][gName]),
	 "content", JsonString(lString),
	 "avatar_url", JsonString("https://i.imgur.com/4M34hi2.png")
	),
	.headers = RequestHeaders()
);
```

On my localhost (Windows 7, 64bit) it works, the message is sent to discord channel. On Linux machine (Debian 8, 32bit) it fails, with error in server-log file

`ERROR: HTTP error Error in SSL handshake`

Is this related to my build or the machine problem? Maybe user doesn't have access to somewhere ? I am new to this thing, do you know what I can do about it?

**Comment by Southclaws** [comment]
This might be caused by missing SSL certs, you might be able to solve it by installing a certs package.

`sudo apt install ca-certificates` should fix this, it will give the library the correct certificates to sign requests.
