### ISSUE TITLE
Error compiling on Ubuntu 14.04

### ISSUE THREAD

**Issue by xunder0** [Southclaws/pawn-requests#35]
Any solutions for this error?

![Error_compiling](https://user-images.githubusercontent.com/28492178/76557806-7c38e280-649c-11ea-8bbb-8045467bc60b.jpg)

**Comment by Southclaws** [comment]
There isn't a statically linked version unfortunately, I could never get the cpprestsdk (and its dependencies) to build in that way.

You need a compiler that supports C++17, iirc GCC 8.x will do this.

**Comment by xunder0** [comment]
I forwarded your reply to hosting and got this answer:

"I can confirm that we've been looking into this further and the highest compatible version of GCC we've been able to get functioning is 4.8.5. It might be possible to setup GCC 6 with some further perseverance but GCC 8 does not appear to be compatible."

**Comment by Sreyas-Sreelal** [comment]
Try using the Rust version on rust-rewrite branch

**Comment by xunder0** [comment]
I successfully compiled Rust version of plugin.
After sending request I'm getting this error: [requests] [error]: expected value at line 1 column 1
Test script that I use: https://pastebin.com/raw/h8MfUuCK

**Comment by xunder0** [comment]
Oh I see now. I'm blind.
