### ISSUE TITLE
Error in SSL handshake

### ISSUE THREAD

**Issue by Papawy** [Southclaws/pawn-requests#36]
Hello,

While compiling and running on both Archlinux (sampctl version 1.8.39) and Ubuntu 18.04 I came across this error:
`ERROR: HTTP error Error in SSL handshake`. I saw the issue #34 but it didn't helped. I saw an issue related to cpprestsdk (Azure/azure-storage-cpp#197) and putting a symlink for `/usr/local/ssl` to `/etc/ssl` did the trick on Archlinux. I don't know why it doesn't check in `/etc/ssl` as it seems standard.

I don't know if you have a solution for this, but anyway it may help some people to solve this issue.

**Comment by Southclaws** [comment]
Thanks for sharing your solution! Not many people do this so it's very much appreciated.

That is indeed a very unhelpful error message. I'm wondering if the Rust branch also runs into this or if it's specifically an issue with cpprestsdk. I'd like to make that the default branch going forward anyway.

**Comment by mousseou** [comment]
Met the same issue with pawn-requests tag/version 0.8.7 on Ubuntu 18.04, and can attest that `sudo ln /etc/ssl /usr/local/ssl` fixed this. Thanks!
