### ISSUE TITLE
Russian characters in response

### ISSUE THREAD

**Issue by YmerDev** [Southclaws/pawn-requests#37]
Hey.

Are they supported? Currently getting something like that.
<img width="402" alt="Снимок экрана 2020-04-14 в 1 13 53 PM" src="https://user-images.githubusercontent.com/18898483/79219038-cc1b1880-7e51-11ea-9eb7-1170370ffe2e.png">

Is there is some ways to convert UTF-8 to CP1251 (or ansi? i don't actually know how it's called) 

CP1251 works well in SAMP, but UTF-8 string doesn't. :(

**Comment by Southclaws** [comment]
If your content type and server response is set to UTF-8, then everything is UTF-8.

You can either convert on the server side or the client side. Either way, the plugin doesn't manipulate the data in any way (and shouldn't, it's outside of the scope of this plugin to handle encoding conversions).

**Comment by YmerDev** [comment]
Encoding makes no sense. Well. This issue not actual anymore.
