### ISSUE TITLE
server crashed

### ISSUE THREAD

**Issue by Dmitriy51** [Southclaws/pawn-requests#38]
exemple:
new WebSocket: ws = WebSocketClient("ws://56.45.678.65:46657/websocket", "test");
WebSocketSend(ws, "hello server");

server_ log: [06:11:30] ERROR: WebSocketClient failed: set_fail_handler: 9: Timer Expired
server shutdown

**Comment by Dmitriy51** [comment]
I use plugin verison 0.8.7

**Comment by ADRFranklin** [comment]
Websocket client natives are now deprecated. you should instead use HTTP requests to hit endpoints and emit websocket events from that request.
