### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by sabaapxazava** [Southclaws/pawn-requests#49]
Failed (/lib/i386-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by plugins/requests.so))

**Comment by ADRFranklin** [comment]
Your system has an older version of glib, what distro and distro version are you on?

**Comment by ADRFranklin** [comment]
@sabaapxazava I have rebuilt the recent release with an older version of glibc, so this should be fixed now.
