### ISSUE TITLE
libc.so.6: version `GLIBC_2.33' not found

### ISSUE THREAD

**Issue by VIRUXE** [Southclaws/pawn-requests#51]
So I've read #50 and #49

I'm running a fresh build of Debian 11 Bullseye. I don't have version 2.33 or 3.4.29 of GLIBC.

Now I'm guessing if I compile it myself maybe it will use the latest version. But just running `task` just leads me to other errors.

```
task: [default] cmake .. -DCMAKE_BUILD_TYPE=Debug
CMake Error at CMakeLists.txt:1 (include):
  include could not find load file:

    /root/plugins/pawn-requests-0.10.0/conanbuildinfo.cmake


CMake Error at CMakeLists.txt:2 (conan_basic_setup):
  Unknown CMake command "conan_basic_setup".


CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.18)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
```

I installed Conan via `python3 -m pip install conan`

**Comment by ADRFranklin** [comment]
You should of used the Earthly cli tool to build the image, as this would of done all the stages for you, all you needed to do was modify the Earthfile image to build specifically for you.

**Comment by VIRUXE** [comment]
Thank you. I'll keep that in mind if I need to run this on Debian again.
