### ISSUE TITLE
Freezes Randomly

### ISSUE THREAD

**Issue by marcelog09** [Southclaws/pawn-requests#54]
My server freezes randomly, from 2x a day, to 1x a day, or even a whole day without any. In the event of a freeze, I am forced to turn it off and on again, as it does not defrost on its own. The 'Crashdetect' does not report any from gamemode function that may be "slow" at the time of freezing.

Q: How do I know the problem may have to do with this plugin (requests)?
A: I tested the server without this plugin (requests) for 1 week and the problem did not occur.

plugin version used: 0.10.0
Operating System: Windows Server 2019
Plugins used: 
mysql
discord-connector
sampvoice
log-plugin
sscanf
MapAndreas
streamer
chrono
SAMPSON - some old scripts (includes) still use this plugin, can it be conflicted with a plugin requests?
pawncmd
pawnregex
pawnraknet
pawn-memory
requests

**Comment by galax-one** [comment]
Maybe check in your code where you use the library then post with some real issue??
