### ISSUE TITLE
Crash on fails WebSocket connection

### ISSUE THREAD

**Issue by vsergeenko777** [Southclaws/pawn-requests#9]
WebSocketClient/JsonWebSocketClient function causes the crash if a connection to WebSocket server was not established. Also, the loss of the established connection causes crash.

> [15/06/2018 03:40:36] [debug] Server crashed while executing test.amx
> [15/06/2018 03:40:36] [debug] AMX backtrace:
> [15/06/2018 03:40:36] [debug] #0 native WebSocketClient () from requests.DLL
> [15/06/2018 03:40:36] [debug] #1 0001601c in WebSocketInit () at test.pwn:108
> [15/06/2018 03:40:36] [debug] #2 00056aa4 in public OnGameModeInit () at test.pwn:88
> [15/06/2018 03:40:37] [debug] Native backtrace:
> [15/06/2018 03:40:37] [debug] #0 77ecd97a in ?? () from C:\Windows\SYSTEM32\ntdll.dll
> [15/06/2018 03:40:37] [debug] #1 77e9b9b6 in ?? () from C:\Windows\SYSTEM32\ntdll.dll
> [15/06/2018 03:40:37] [debug] #2 6e4504db in ?? () from C:\Windows\SYSTEM32\MSVCP140.dll
> [15/06/2018 03:40:37] [debug] #3 6baa6b06 in ?? () from plugins\requests.DLL
> [15/06/2018 03:40:37] [debug] #4 6baacc61 in ?? () from plugins\requests.DLL
> [15/06/2018 03:40:37] [debug] #5 6baa7a96 in ?? () from plugins\requests.DLL
> [15/06/2018 03:40:37] [debug] #6 6baad9e8 in ?? () from plugins\requests.DLL
> [15/06/2018 03:40:37] [debug] #7 6baa096c in ?? () from plugins\requests.DLL
> [15/06/2018 03:40:37] [debug] #8 6bab26be in ?? () from plugins\requests.DLL
> [15/06/2018 03:40:37] [debug] #9 004010b6 in ?? () from samp-server-cr.exe
> [15/06/2018 03:40:37] [debug] #10 6c1ad60a in ?? () from plugins\crashdetect.DLL

**Comment by Southclaws** [comment]
Thanks, I've added a test case for this and fixed it in 0.6.2.

**Comment by vsergeenko777** [comment]
Thanks. There is one more problem. The WebSocketSend function causes crash if the connection to the WebSocket server has been lost. I propose to add the callbacks OnWebSocketConnect/OnWebSocketDisconnect.

**Comment by AGraber** [comment]
fix pls
